const destinations = [
	{ name: "Albania" },
	{ name: "Åland Islands" },
	{ name: "Algeria" },
	{ name: "American Samoa" },
	{ name: "Andorra" },
	{ name: "Angola" },
	{ name: "Anguilla" },
	{ name: "Antarctica" },
	{ name: "Antigua and Barbuda" },
	{ name: "Argentina" },
	{ name: "Armenia" },
	{ name: "Aruba" },
	{ name: "Australia" },
	{ name: "Austria" },
	{ name: "Azerbaijan" },
	{ name: "Bahamas (the)" },
	{ name: "Bahrain" },
	{ name: "Bangladesh" },
	{ name: "Barbados" },
	{ name: "Belarus" },
	{ name: "Belgium" },
	{ name: "Belize" },
	{ name: "Benin" },
	{ name: "Bermuda" },
	{ name: "Bhutan" },
	{ name: "Bolivia (Plurinational State of)" },
	{ name: "Bonaire, Sint Eustatius and Saba" },
	{ name: "Bosnia and Herzegovina" },
	{ name: "Botswana" },
	{ name: "Bouvet Island" },
	{ name: "Brazil" },
	{ name: "British Indian Ocean Territory (the)" },
	{ name: "Brunei Darussalam" },
	{ name: "Bulgaria" },
	{ name: "Burkina Faso" },
	{ name: "Burundi" },
	{ name: "Cabo Verde" },
	{ name: "Cambodia" },
	{ name: "Cameroon" },
	{ name: "Canada" },
	{ name: "Cayman Islands (the)" },
	{ name: "Central African Republic (the)" },
	{ name: "Chad" },
	{ name: "Chile" },
	{ name: "China" },
	{ name: "Christmas Island" },
	{ name: "Cocos (Keeling) Islands (the)" },
	{ name: "Colombia" },
	{ name: "Comoros (the)" },
	{ name: "Congo (the Democratic Republic of the)" },
	{ name: "Congo (the)" },
	{ name: "Cook Islands (the)" },
	{ name: "Costa Rica" },
	{ name: "Croatia" },
	{ name: "Cuba" },
	{ name: "Curaçao" },
	{ name: "Cyprus" },
	{ name: "Czechia" },
	{ name: "Côte d'Ivoire" },
	{ name: "Denmark" },
	{ name: "Djibouti" },
	{ name: "Dominica" },
	{ name: "Dominican Republic (the)" },
	{ name: "Ecuador" },
	{ name: "Egypt" },
	{ name: "El Salvador" },
	{ name: "Equatorial Guinea" },
	{ name: "Eritrea" },
	{ name: "Estonia" },
	{ name: "Eswatini" },
	{ name: "Ethiopia" },
	{ name: "Falkland Islands (the) [Malvinas]" },
	{ name: "Faroe Islands (the)" },
	{ name: "Fiji" },
	{ name: "Finland" },
	{ name: "France" },
	{ name: "French Guiana" },
	{ name: "French Polynesia" },
	{ name: "French Southern Territories (the)" },
	{ name: "Gabon" },
	{ name: "Gambia (the)" },
	{ name: "Georgia" },
	{ name: "Germany" },
	{ name: "Ghana" },
	{ name: "Gibraltar" },
	{ name: "Greece" },
	{ name: "Greenland" },
	{ name: "Grenada" },
	{ name: "Guadeloupe" },
	{ name: "Guam" },
	{ name: "Guatemala" },
	{ name: "Guernsey" },
	{ name: "Guinea" },
	{ name: "Guinea-Bissau" },
	{ name: "Guyana" },
	{ name: "Haiti" },
	{ name: "Heard Island and McDonald Islands" },
	{ name: "Holy See (the)" },
	{ name: "Honduras" },
	{ name: "Hong Kong" },
	{ name: "Hungary" },
	{ name: "Iceland" },
	{ name: "India" },
	{ name: "Indonesia" },
]
export default destinations
